parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"fk2o":[function(require,module,exports) {
function r(r){if(Array.isArray(r)){for(var e=0,n=new Array(r.length);e<r.length;e++)n[e]=r[e];return n}}module.exports=r;
},{}],"rp83":[function(require,module,exports) {
function t(t){if(Symbol.iterator in Object(t)||"[object Arguments]"===Object.prototype.toString.call(t))return Array.from(t)}module.exports=t;
},{}],"v+5/":[function(require,module,exports) {
function e(){throw new TypeError("Invalid attempt to spread non-iterable instance")}module.exports=e;
},{}],"03Yt":[function(require,module,exports) {
var r=require("./arrayWithoutHoles"),e=require("./iterableToArray"),a=require("./nonIterableSpread");function o(o){return r(o)||e(o)||a()}module.exports=o;
},{"./arrayWithoutHoles":"fk2o","./iterableToArray":"rp83","./nonIterableSpread":"v+5/"}],"e7Sb":[function(require,module,exports) {
function r(r){if(Array.isArray(r))return r}module.exports=r;
},{}],"nyVk":[function(require,module,exports) {
function r(r,t){var n=[],e=!0,l=!1,o=void 0;try{for(var u,a=r[Symbol.iterator]();!(e=(u=a.next()).done)&&(n.push(u.value),!t||n.length!==t);e=!0);}catch(i){l=!0,o=i}finally{try{e||null==a.return||a.return()}finally{if(l)throw o}}return n}module.exports=r;
},{}],"yJnk":[function(require,module,exports) {
function t(){throw new TypeError("Invalid attempt to destructure non-iterable instance")}module.exports=t;
},{}],"xw6J":[function(require,module,exports) {
var r=require("./arrayWithHoles"),e=require("./iterableToArrayLimit"),i=require("./nonIterableRest");function t(t,a){return r(t)||e(t,a)||i()}module.exports=t;
},{"./arrayWithHoles":"e7Sb","./iterableToArrayLimit":"nyVk","./nonIterableRest":"yJnk"}],"AaGI":[function(require,module,exports) {
"use strict";var n=t(require("@babel/runtime/helpers/toConsumableArray")),e=t(require("@babel/runtime/helpers/slicedToArray"));function t(n){return n&&n.__esModule?n:{default:n}}var r="airbus-showcase-v4",a=[".","./animationData/a350.json","./animationData/ariane.json","./animationData/iss.json","./animationData/orion.json"];self.addEventListener("install",function(t){t.waitUntil(caches.open(r).then(function(t){return fetch("./parcel-manifest.json").then(function(n){return n.json()}).then(function(r){var u=Object.entries(r).filter(function(n){return!(0,e.default)(n,1)[0].endsWith(".map")}).map(function(n){var t=(0,e.default)(n,2);t[0];return t[1]});return t.addAll([].concat(a,(0,n.default)(u)))})}).then(function(){return self.skipWaiting()}))}),self.addEventListener("activate",function(n){var e=[r];n.waitUntil(caches.keys().then(function(n){var t=n.map(function(n){if(!e.includes(n))return caches.delete(n)});return Promise.all(t)}))});var u=function(n){return new Promise(function(e,t){n.status>=200&&n.status<300||0===n.status?e(n):t(n.statusText)})},i=function(n){return"chrome-extension:"!==new URL(n.url).protocol},o=function(n){return 0!==n.status&&"opaque"!==n.type},s=function(n){return fetch(n.request).catch(function(){var n=JSON.stringify({error:"Sorry, you're offline. Try again once you have a working internet connection."});return new Response(n,{status:404,statusText:"Not Found",headers:{"Content-Type":"application/json"}})})},c=function(n,e){return fetch(n.request).then(u).then(function(t){return o(t)&&e.put(n.request,t.clone()),t}).catch(function(){return e.match(n.request)})};self.addEventListener("fetch",function(n){if(i(n.request)){var e=n.request.url,t=e.includes("?")?new Request(e.substring(e.indexOf("?")+1)):n.request;n.respondWith(caches.match(t).then(u).then(function(e){return caches.open(r).then(function(t){return navigator.onLine&&c(n,t),e})}).catch(function(){return caches.open(r).then(function(e){return c(n,e)})}))}else n.respondWith(s(n))});
},{"@babel/runtime/helpers/toConsumableArray":"03Yt","@babel/runtime/helpers/slicedToArray":"xw6J"}]},{},["AaGI"], null)
//# sourceMappingURL=/airbus-showcase/service-worker.js.map